### ISSUE TITLE
Rename `eik package` to `eik publish`

### ISSUE THREAD

**Issue by digitalsadhu** [eik-lib/cli#152]
`eik package` made more sense in the early stages when Eik handled bundling. Best to rename it to `eik publish`

**Comment by digitalsadhu** [comment]
Thinking about this further, unsure if we want to make this change. There is a certain symmetry in the commands currently. We have `eik npm`, `eik npm-alias`, `eik map`, `eik map-alias` and `eik package` and `eik package-alias`. If we change package to publish the package/package-alias part wont align and I don't necessarily think that `eik publish-alias` makes sense. Feels like you are making an alias for a package, not a publish. Or... not sure?

@stipsan

**Comment by stipsan** [comment]
I agree, I wasn't aware of `eik map` or `eik map-alias` back when I brought this up. I think we should stick to `eik package` since we're essentially "publishing" 3 separate things in eik and the distinction between `npm`, `package` and `map` makes sense.

**Comment by digitalsadhu** [comment]
👍
