### ISSUE TITLE
List the files that get published

### ISSUE THREAD

**Issue by wkillerud** [eik-lib/cli#551]
It would be nice to have an output similar to that of `npm publish` which lists the files that get included in the published asset.

Example output from `npm`:

```
[7:47:50 AM] [semantic-release] [@semantic-release/npm] › ℹ  Creating npm package version 2.0.38
npm notice
npm notice 📦  @eik/cli@2.0.38
npm notice === Tarball Contents ===
npm notice 44.2kB CHANGELOG.md
npm notice 4.3kB  classes/alias.js
npm notice 887B   classes/index.js
npm notice 5.0kB  classes/version.js
npm notice 3.2kB  commands/init.js
npm notice 3.9kB  commands/version.js
npm notice 2.0kB  formatters/alias.js
npm notice 1.2kB  index.js
npm notice 2.2kB  package.json
npm notice 134B   readme.md
npm notice 390B   utils/get-cwd.js
npm notice 411B   utils/hash/compare.js
npm notice === Tarball Details ===
npm notice name:          @eik/cli
npm notice version:       2.0.38
npm notice filename:      @eik/cli-2.0.38.tgz
npm notice package size:  30.0 kB
npm notice unpacked size: 141.9 kB
npm notice shasum:        87a20f716ac052f64ad15616dff89d05f6497499
npm notice integrity:     sha512-LdWE5cDnpuJu6[...]vZIfgV8fK2pqg==
npm notice total files:   57
npm notice
eik-cli-2.0.38.tgz
```

**Comment by digitalsadhu** [comment]
![Screenshot 2024-08-05 at 10 24 17](https://github.com/user-attachments/assets/aacbbe06-4d3f-4a9f-ab87-faa725935a6f)

The publish command lists all the files that got published but I notice that you dont get the same kind of output if you are using the Eik semantic release plugin. Maybe thats what you are referring to? Or perhaps you mean it should just be done differently?

**Comment by wkillerud** [comment]
It might have been from semantic-release, I honestly don't remember 😅 In any case, since the CLI does list the files I'll close up this issue.
