### ISSUE TITLE
Add a `--dry-run` flag to `publish`

### ISSUE THREAD

**Issue by wkillerud** [eik-lib/cli#552]
Related to #551 it would be nice to have a `--dry-run` option so you can confirm that the published asset includes the expected files before doing the actual publish.

**Comment by digitalsadhu** [comment]
There's already a --dry-run command. Does it not do what's needed?

**Comment by wkillerud** [comment]
Oh there is! Helps if I read `--help` 🤦 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnI3Ym5pbTd6bXdoMWN5MTVwMDNlZGh5bWxsdnZxejdnbDg4bGQwcyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3oz8xrMY2OW8ajE6Os/giphy.gif)
