### ISSUE TITLE
Add an option to pass in a path to a config

### ISSUE THREAD

**Issue by wkillerud** [eik-lib/cli#553]
Use case: publish images or other somewhat stable assets with a different Eik config. Versioned and published separately from the application code.

The CLI would need to support a `-c/--config` flag for relevant commands (`version` and `publish` at least).

**Comment by digitalsadhu** [comment]
Should the cwd then be the directory you are running the command in, or the root of the provided config file? Presumably the directory you are running the command from or the cwd as provided by the --cwd flag?
