### ISSUE TITLE
Add a `-v` and `--version` argument

### ISSUE THREAD

**Issue by wkillerud** [eik-lib/cli#564]
The current fallback output does include the version number, but it would be nice to get a minimal output like for `npm -v`.

```
$ npm -v
10.2.3
```

**Comment by digitalsadhu** [comment]
both eik version and eik -v are in use currently for the eik version command that increments major/minor/patch versions of a package. I might (since we are doing breaking changes) yoink -v away from the version command and repurpose it for listing the version
