### ISSUE TITLE
Publishing fails with unauthorized warning when server is defined in assets.json file

### ISSUE THREAD

**Issue by trygve-lie** [eik-lib/cli#98]
I've installed the client globally, then logged in to the server  (ex; `https://cdn.ex.com`).

Then I have a repo where server is defined in assets.json like so:

```json
{
  "name": "foo",
  "major": 1,
  "server": "https://cdn.ex.com/",
  "js": {
    "input": "./static/client.js",
    "options": {}
  },
  "css": {
    "input": "",
    "options": {}
  }
}
```

When running ` eik package` I get the following error:

```sh
✖ Unable to upload zip file to server
⚠ Client unauthorized with server
```

If I remove `server` in the assets.json file, publishing works.

**Comment by digitalsadhu** [comment]
Is this still an issue @trygve-lie? I've since published several times and not seeing this issue at my end.
